Update deploy-standalone-plugins.yml

diff --git a/.github/workflows/deploy-standalone-plugins.yml b/.github/workflows/deploy-standalone-plugins.yml
--- a/.github/workflows/deploy-standalone-plugins.yml
+++ b/.github/workflows/deploy-standalone-plugins.yml
@@ -77,6 +77,22 @@ jobs:
         run: |
           echo "PLUGIN_VERSION=$(jq -r '."${{ matrix.plugin }}"' manifest.json)" >> $GITHUB_ENV
 
+      - name: Prepare plugin to deploy
+        run: |
+          PLUGIN_VERSION_WPORG=$(curl -sSL https://api.wordpress.org/plugins/info/1.0/${{ matrix.plugin }}.json --retry 3 --retry-delay 5 --retry-all-errors --fail | jq -r '.version')
+
+          # Bail if plugin version is not found.
+          if [ -z "$PLUGIN_VERSION_WPORG" ]; then
+            echo "::error::Could not retrieve ${{ matrix.plugin }} information from WordPress.org. The plugin may not exist or the API may be down."
+            exit 1
+          fi
+
+          # Bail if plugin is already up to date.
+          if [ "$PLUGIN_VERSION_WPORG" = "$PLUGIN_VERSION" ]; then
+            echo "::notice::The plugin ${{ matrix.plugin }} is already up to date on WordPress.org."
+            exit 0
+          fi
+
       - name: Create zip file
         run: |
           mkdir -p ./build/dist
@@ -108,12 +124,12 @@ jobs:
       - name: Deploy Plugin - ${{ matrix.plugin }}
         uses: 10up/action-wordpress-plugin-deploy@stable
         with:
-          dry-run: true
+          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run || false }}
         env:
           SLUG: ${{ matrix.plugin }}
           VERSION: ${{ env.PLUGIN_VERSION }}
-          SVN_USERNAME: 'user'
-          SVN_PASSWORD: 'pass'
+          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
+          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
           BUILD_DIR: ./build/${{ matrix.plugin }}
           ASSETS_DIR: ./plugins/${{ matrix.plugin }}/.wordpress-org
 
@@ -140,13 +156,33 @@ jobs:
       matrix:
         plugin: ${{ fromJSON(needs.pre-run.outputs.matrix) }}
     steps:
+      - name: Check artifact existence
+        id: artifact-existence
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const getArtifact = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts{?name}', {
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              run_id: context.runId,
+              name: ${{ matrix.plugin }}
+            });
+
+            if (getArtifact.status !== 200) {
+              throw new Error(`Invalid response from GitHub API: ${getArtifact.status}`);
+            }
+
+            core.setOutput('exists', getArtifact.data.artifacts.length > 0);
+
       - name: Download artifact
+        if: steps.artifact-existence.outputs.exists == 'true'
         uses: actions/download-artifact@v4
         with:
           name: ${{ matrix.plugin }}
           path: ./build/dist
 
       - name: Upload release assets
+        if: steps.artifact-existence.outputs.exists == 'true'
         uses: softprops/action-gh-release@v1
         with:
           files: |
